// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmjbYQZcC5iELlTQpMsrnMOZ--A-KrPGw',
    appId: '1:580597870948:web:962832bf410fcc40738a71',
    messagingSenderId: '580597870948',
    projectId: 'olam-grains',
    authDomain: 'olam-grains.firebaseapp.com',
    storageBucket: 'olam-grains.appspot.com',
    measurementId: 'G-0XQG7SJ3PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALyQarBe82selvZq_lAkhJU4arinHZf28',
    appId: '1:580597870948:android:91e8cdc87c44ba7d738a71',
    messagingSenderId: '580597870948',
    projectId: 'olam-grains',
    storageBucket: 'olam-grains.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0WrqvlOWOKXhB0OiP13J6CgFhFQEC27I',
    appId: '1:580597870948:ios:41c7b4a4809e1d09738a71',
    messagingSenderId: '580597870948',
    projectId: 'olam-grains',
    storageBucket: 'olam-grains.appspot.com',
    iosClientId: '580597870948-v67epjnsbr4lvgc1hh0a9epnlfmh6t5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.olamGrains',
  );
}
